### ISSUE TITLE
Counting by repName

### ISSUE THREAD

**Issue by rn383** [mlbendall/telescope#17]
Hi,
I'm trying to run telescope assign using --attribute repName rather than --attribute gene_id which I usually use. This has produced this error:

Traceback (most recent call last):
  File "/home/rn383/.conda/envs/bioinfo/bin/telescope", line 11, in <module>
    load_entry_point('telescope-ngs==1.0.3', 'console_scripts', 'telescope')()
  File "/home/rn383/.conda/envs/bioinfo/lib/python3.7/site-packages/telescope/__main__.py", line 95, in main
    args.func(args)
  File "/home/rn383/.conda/envs/bioinfo/lib/python3.7/site-packages/telescope/telescope_assign.py", line 207, in run
    annot = Annotation(opts.gtffile, opts.attribute)
  File "/home/rn383/.conda/envs/bioinfo/lib/python3.7/site-packages/telescope/utils/_annotation_intervaltree.py", line 41, in __init__
    if attr[self.key] not in self.loci:
KeyError: 'repName'

The command I used was:
assign --attribute repName --outdir <output directory> --exp_tag <cellname> --theta_prior 200000 --max_iter 200 <BAMfile> <GTFannotationfile>

The BAM files were produced using STAR and the GTF is the same one used in the Telescope paper. Any help or suggestions much appreciated!

**Comment by hchintalapudi** [comment]
I get the same issue!
Any workaround @rn383 ?

Thanks

Himanshu

**Comment by mlbendall** [comment]
The issue here is that some of the lines in the annotation do not contain the attribute "repName". You can solve this by removing all the GTF lines that do not have "repName" assigned. For my annotation [HERV_rmsk.hg38.v2](https://github.com/mlbendall/telescope_annotation_db/tree/master/builds/HERV_rmsk.hg38.v2) the lines that are missing "repName" are "gene" features. You can make a suitable annotation like this:

```
grep 'repName' transcripts.gtf > newtranscripts.gtf
```

I will also pushing up a fix that automatically skips lines missing the attribute (with a warning).

**Comment by hchintalapudi** [comment]
Thanks, @mlbendall!
Will try that.
