### ISSUE TITLE
scRNA data from poly A priming sequencing

### ISSUE THREAD

**Issue by HJ234** [mlbendall/telescope#41]
Hi, Thanks for the great program.
I was just wondering if this program can be used on single cell data generated with dT priming (attaches to poly A tail) and around 300bp sequenced from the 5' end. 
From some literature search, it seems like some HERV sequences lack the poly A tail, in which the transcripts will not be sequenced. 
Have you experienced any differences in expression levels between HERV sequences with poly A tails and those without in real data?

**Comment by mlbendall** [comment]
We have split off our single cell project into a separate repo ("stellarscope"), it should be available soon.
polyA selection, whether for bulk or single-cell, does uncover many HERVs, though we are unsure if some of these are due to internal homopolymer/polyA that are intrinsic to some retrovirus/ERV families.
